### ISSUE TITLE
error

### ISSUE THREAD

**Issue by glopratchet** [Eiskis/bellevue#1]
ERROR in ./node_modules/sass-vars-to-js-loader?preserveKeys=false!./src/styles/constants.scss
" (1:22)uild failed: Error: Can't handle character: "
    at InputStream.err (C:\Users\wadodd\Desktop\bellevue\node_modules\scss-parser\dist\input-stream.js:122:13)
    at Object.err (C:\Users\wadodd\Desktop\bellevue\node_modules\scss-parser\dist\input-stream.js:161:20)
    at TokenStream.err (C:\Users\wadodd\Desktop\bellevue\node_modules\scss-parser\dist\token-stream.js:297:40)
    at TokenStream.read_next (C:\Users\wadodd\Desktop\bellevue\node_modules\scss-parser\dist\token-stream.js:352:12)
    at TokenStream.peek (C:\Users\wadodd\Desktop\bellevue\node_modules\scss-parser\dist\token-stream.js:248:26)
    at TokenStream.eof (C:\Users\wadodd\Desktop\bellevue\node_modules\scss-parser\dist\token-stream.js:282:26)
    at Object.eof (C:\Users\wadodd\Desktop\bellevue\node_modules\scss-parser\dist\token-stream.js:631:16)
    at Parser.parse_stylesheet (C:\Users\wadodd\Desktop\bellevue\node_modules\scss-parser\dist\parse.js:266:27)
    at module.exports (C:\Users\wadodd\Desktop\bellevue\node_modules\scss-parser\dist\parse.js:748:17)
    at Object.parse (C:\Users\wadodd\Desktop\bellevue\node_modules\scss-parser\dist\index.js:27:10)
    at transformSASSFile (C:\Users\wadodd\Desktop\bellevue\node_modules\sass-vars-to-js-loader\src\extract.js:29:25)
    at SassVariablesExtract (C:\Users\wadodd\Desktop\bellevue\node_modules\sass-vars-to-js-loader\src\extract.js:149:27)
    at Object.module.exports (C:\Users\wadodd\Desktop\bellevue\node_modules\sass-vars-to-js-loader\index.js:31:3)
 @ ./src/config/s

**Comment by Eiskis** [comment]
Which node version are you using?

**Comment by Eiskis** [comment]
Closing this due to no additional info provided. Feel free to reopen if the issue persists and you can provide more details on how to replicate.
